# version: '3.8'
services:
  lemma_eta_nerc:
    container_name: lemma_eta_nerc
    build: .
    ports:
      - "8010:8010"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8010
    # use internal network backend_net
    networks:
      - backend_net
      # - temporal_network

networks:
  # internal backend network
  backend_net: 
    external: true
  # create a new network to access external internet
  # temporal_network:
  #   driver: bridge
